### ISSUE TITLE
FEATURE: Add search bar on all todo's page

### ISSUE THREAD

**Issue by shubhagarwal1** [10kumaranurag01/todo-done#12]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

yes, the search bar on the all todo page is not present, add it will help user to navigate between diffent todo's efficiently

### Proposed Solution

will add a search bar below add todo button on all todo page

### Screenshots

![Screenshot 2024-10-01 at 8 59 53 PM](https://github.com/user-attachments/assets/7134c01c-8c12-4693-b257-ed20ae36f91f)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

will add a search bar feature on the all todo's page which will significatly show the suggestion when charecters will get typed inside the search bar.

**Comment by akshatshukla13** [comment]
Hi @10kumaranurag01 ,

I'd like to work on this issue, I can implement the search bar. Also, I came across a few more bugs and features I think can be improved in both the server and client repo. Is it okay if I fix them too? Where can i approach you regarding so?

Let me know!

Akshat

**Comment by 10kumaranurag01** [comment]
@akshatshukla13 The search bar is already implemented, if you see any other bugs or improvements you can create issues and i will review and assign it to you.

**Comment by akshatshukla13** [comment]
@10kumaranurag01 the status button at adding a todo card is unnecessary. It is only required after a todo is added.
