### ISSUE TITLE
[FEATURE] <Adding a delete button>

### ISSUE THREAD

**Issue by Ketanop321** [10kumaranurag01/todo-done#14]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Adding a delete or remove button

### Proposed Solution

add a delete button   todo cards

### Do you want to work on this issue?

Yes

**Comment by 10kumaranurag01** [comment]
@Ketanop321 Deleting a todo is already present
