### ISSUE TITLE
[FEATURE] Add loading screen and integrate to app

### ISSUE THREAD

**Issue by Kalevins** [10kumaranurag01/todo-done#15]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes, it is not currently implemented.

### Proposed Solution

It is proposed to implement a loading screen and integrate it with the application's fetch requests.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

A component would be made with the loading screen, a context with the state that changes the loading and it would be made in an interceptor of the fetch requests changing said state.

**Comment by 10kumaranurag01** [comment]
@Kalevins Go ahead and fork it and make a PR. Happy Contributing!

**Comment by 10kumaranurag01** [comment]
@Kalevins In dark mode screen goes all white when loader shows. Can you fix that?

**Comment by Kalevins** [comment]
Sure @10kumaranurag01, i can fix that

**Comment by 10kumaranurag01** [comment]
@Kalevins Cool, Go ahead.
