### ISSUE TITLE
[FEATURE] Implement Dark Mode and Light Mode Toggle

### ISSUE THREAD

**Issue by 10kumaranurag01** [10kumaranurag01/todo-done#16]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes, the feature request is related to the unavailability of a dark and light mode toggle in the current application. This missing functionality affects users who prefer different visual themes based on their environment or device settings. For instance:

- **User Comfort**: Some users find it easier to view content in dark mode, especially in low-light environments, while others prefer light mode for better visibility in bright conditions.
- **Customization and Accessibility**: Providing a choice between dark and light modes enhances the user experience by allowing customization according to individual preferences, improving accessibility for users with specific visual needs.
- **System Preference Support**: Modern applications often sync with the system’s appearance settings. Without this feature, the application may feel outdated or less user-friendly compared to other apps that support automatic theme adjustments.

By implementing this feature, the application would meet users' expectations for customization, improve usability, and align with modern UI/UX standards.

### Proposed Solution

To implement dark and light mode using ShadCN (ShadCN/UI components for styling), you can use a combination of CSS variables, Tailwind CSS’s dark mode support, and ShadCN components. Below is a step-by-step guide for the proposed solution:

### Do you want to work on this issue?

No

**Comment by 10kumaranurag01** [comment]
Go ahead @Tony-ArtZ , fork the repo and make  a PR with a new branch. Happy Contributing 🥳

**Comment by 10kumaranurag01** [comment]
@Tony-ArtZ Make sure the whole application responds to the toggle with text- colors too. Happy Contributing 😊

**Comment by toufiqfarhan0** [comment]
Can you please assign me

**Comment by 10kumaranurag01** [comment]
@Tony-ArtZ Have you completed it? Because @toufiqfarhan0 is willing to get this issue assigned.

**Comment by 10kumaranurag01** [comment]
@toufiqfarhan0 Can you give a screen recording after logging in also? So that i can check every page of the application

**Comment by toufiqfarhan0** [comment]
> @toufiqfarhan0 Can you give a screen recording after logging in also? So that i can check every page of the application

Sure ser !!!

**Comment by toufiqfarhan0** [comment]
@10kumaranurag01 

https://github.com/user-attachments/assets/6ee7e743-4c10-46df-befa-241a709de5f5

**Comment by 10kumaranurag01** [comment]
@toufiqfarhan0 Sorry but the issue is already assigned to @Tony-ArtZ, let him confirm once

**Comment by 10kumaranurag01** [comment]
@toufiqfarhan0 You can check for new issue or create one if you see one. Thank You!

**Comment by 10kumaranurag01** [comment]
@toufiqfarhan0 Sure

**Comment by toufiqfarhan0** [comment]
> @toufiqfarhan0 Sure

you closed it reopen i wanna make it draft

**Comment by 10kumaranurag01** [comment]
@Tony-ArtZ As we are not responding to the comments and more issues are depending on this issue, we are assigning this issue to @toufiqfarhan0 

@toufiqfarhan0 Kindly pull from the latest main branch and take care of the new homepage responding to the dark/light toggle
