### ISSUE TITLE
[BUG] Input Fields Are Not Working

### ISSUE THREAD

**Issue by Abhiraj-Sardar** [10kumaranurag01/todo-done#17]
### Description

When you click on the Input fields to add a new todo, the input fields are not working...
The Screenshot is provided below...

![Input-Fields](https://github.com/user-attachments/assets/63191465-5603-43fb-9854-9071ab453fff)

https://github.com/user-attachments/assets/8caa033d-2e13-45df-82d2-a758fe1345a2

here The **Task Title** and **Task Description** Input Fields are not working...

### Where did you find this bug?

Local Dev and Live Website Both

**Comment by rakimsth** [comment]
@10kumaranurag01 / @Abhiraj-Sardar , Can I do this issue? If yes, please assign this issue to me.

**Comment by Abhiraj-Sardar** [comment]
> @10kumaranurag01 / @Abhiraj-Sardar , Can I do this issue? If yes, please assign this issue to me.

@rakimsth  Sure... You can fork this Repo in Your Local System and make Pull Request..

**Comment by rakimsth** [comment]
Great. Consider it done by tomorrow.

**Comment by rakimsth** [comment]
> > @10kumaranurag01 / @Abhiraj-Sardar , Can I do this issue? If yes, please assign this issue to me.
> 
> @rakimsth Sure... You can fork this Repo in Your Local System and make Pull Request..

Great, consider it done...

**Comment by 10kumaranurag01** [comment]
@rakimsth I don't understand what's the issue?

**Comment by Abhiraj-Sardar** [comment]
> @rakimsth I don't understand what's the issue?

@10kumaranurag01 as discussed earlier the input fields are not working....when we try to add a new Todo.

**Comment by 10kumaranurag01** [comment]
@rakimsth I can see it working, may be its a theme issue, turn on dark mode once and verify your issue

**Comment by rakimsth** [comment]
> @rakimsth I can see it working, may be its a theme issue, turn on dark mode once and verify your issue

Yes, @10kumaranurag01 , its related to css rather than functionality. So, I will fix the CSS and make it visible.

**Comment by 10kumaranurag01** [comment]
@rakimsth The theme issue is assigned already, look for any other open issue or fins a new one, Thanks for your efforts 😊
