### ISSUE TITLE
[FEATURE] Displaying avatar or name of the person in the top right

### ISSUE THREAD

**Issue by ayush-848** [10kumaranurag01/todo-done#18]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

![image](https://github.com/user-attachments/assets/52bdda2c-0d87-4050-bd63-7e736095fe01)

### Proposed Solution

I will display the name near the logout button

### Do you want to work on this issue?

Yes

**Comment by ayush-848** [comment]
@10kumaranurag01 please assign this issue to me

**Comment by Ashu1823** [comment]
Hi..
Intrested to work in this issue.
Can you please assign it to me?

**Comment by 10kumaranurag01** [comment]
@Ashu1823 The oauth functionality is under process, after its get done i will assign you this to show avatar of the user

**Comment by mohit-1710** [comment]
Hi @10kumaranurag01  , Could you please assign this issue to me? I would love to work on it and will ensure to provide the best solution.
