### ISSUE TITLE
[BUG] No closure of dialog box after usage

### ISSUE THREAD

**Issue by Villain45** [10kumaranurag01/todo-done#20]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Live Website

### Version of website/mobile (for example "v1.2.3")

v1

### Description

The calendar dialog box should get closed once the user is done with selecting the required date, similarly the same issue of not closing up the dialog box is found for adding a to-do item or editing one

### Steps to Reproduce

Just try to add or edit a to-do item

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Will be making some changes in handleSubmit function to close the dialog box

**Comment by 10kumaranurag01** [comment]
Go ahead @Villain45 , fork and create a new branch. Happy Contributing!
