### ISSUE TITLE
[BUG] Unnecessary "Select Status" in Add To Do form!!

### ISSUE THREAD

**Issue by akshatshukla13** [10kumaranurag01/todo-done#23]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Local dev environment

### Version of website/mobile (for example "v1.2.3")

v1

### Description

The "Select status" dropdown in the "Add To Do" form seems unnecessary for creating tasks. It would be better to remove it.

### Steps to Reproduce

Steps to Reproduce:
1. Open the "Add To Do" form.
2. The "Select status" field appears, but it’s not needed for adding a task.

### Screenshots

![abc](https://github.com/user-attachments/assets/ba5fc67d-ca7e-4322-bd29-b1c8a54011fd)

### Do you want to work on this issue?

Yes

**Comment by akshatshukla13** [comment]
We can use conditional rendering to show or hide the "Select status" dropdown in the Add To Do form. Several other methods can be implemented.

**Comment by 10kumaranurag01** [comment]
@akshatshukla13 Can you explain in detail what changes you want to do?

**Comment by akshatshukla13** [comment]
@10kumaranurag01 the status button at adding a todo card is unnecessary. It is only required after a todo is added.

**Comment by 10kumaranurag01** [comment]
I think the option to select a status must present, because there can be cases where the user may want to add a task while doing or after completing it to keep track of his/her tasks.
