### ISSUE TITLE
[FEATURE] Update the color schemes. 

### ISSUE THREAD

**Issue by shivamnarkar47** [10kumaranurag01/todo-done#31]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

- It is a nice minimal UI for now. But if we noticed there are alot of mixed colors which don't suite such color schemes. 
- Also the font sizes are very short compared to the required sizes. 
- Loading component has a very low opacity at background resulting in overlapping of text.

### Proposed Solution

- Maintaining the typography design principles.
- Creating a Loading component which will have a better UX.
- Color schemes which can help the user to focus on his todos.

### Screenshots

![image](https://github.com/user-attachments/assets/5ba64617-3dfe-445a-9d68-c5c24f6d1495)

Something like this...

### Do you want to work on this issue?

No

**Comment by 10kumaranurag01** [comment]
@shivamnarkar47 The dark and light theme is under work
