### ISSUE TITLE
[FEATURE] Adding app name to the sidebar header FOR MOBILE DEVICES ONLY

### ISSUE THREAD

**Issue by 10kumaranurag01** [10kumaranurag01/todo-done#33]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes

### Proposed Solution

Adding app name to the sidebar header

### Screenshots

![image](https://github.com/user-attachments/assets/37f370eb-c5d3-4428-b4d5-3218f33c588e)

### Do you want to work on this issue?

No

**Comment by AnanteshG** [comment]
Can I work on this issue?

**Comment by toufiqfarhan0** [comment]
assign me and also resolves #37

**Comment by toufiqfarhan0** [comment]
![image](https://github.com/user-attachments/assets/ee5d5a37-44b5-4629-ab84-7bfe5c876bdf)
You can close this I have fixed this in above PR. You can see
