### ISSUE TITLE
Change default Vercel icon to 📝 icon.

### ISSUE THREAD

**Issue by AnanteshG** [10kumaranurag01/todo-done#35]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Live website

### Version of website/mobile (for example "v1.2.3")

Current version

### Description

The default Vercel Icon is being used as the logo.
Change it to [📝](https://todo-done.anuragg.top/)

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to <replace your> page.
1. On top right side, close to the <Account> menu
1. Some menu are not working properly.
1. Continue...

If you don't know exact steps, include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Screenshots

![image](https://github.com/user-attachments/assets/8a9e8e23-b513-40f7-9363-eae90ac222da)

### Do you want to work on this issue?

Yes

**Comment by 10kumaranurag01** [comment]
@Anantesh Go ahead, fork it and create q new branch and make a PR.
