### ISSUE TITLE
DEVOPS: Configure prettier for code consistency

### ISSUE THREAD

**Issue by akshatshukla13** [10kumaranurag01/todo-done#38]
We should configure [prettier](https://prettier.io/) to consistently format the code cross-IDE and cross-contributor.

**Comment by 10kumaranurag01** [comment]
Go ahead @akshatshukla13, fork the repository, create a new branch and make a PR .

**Comment by 10kumaranurag01** [comment]
@akshatshukla13 Error while building
![Screenshot from 2024-10-03 17-19-18](https://github.com/user-attachments/assets/ca3a9c05-697b-47e5-af83-6ac31a3b2d69)

**Comment by akshatshukla13** [comment]
Let me check it again.

**Comment by XronTrix10** [comment]
@akshatshukla13 @10kumaranurag01 

The `.eslintrc.js` file should be removed and the `.eslintrc.json` file should be configured properly.

You can refer [This Gist](https://gist.github.com/XronTrix10/587a2b28953ea262799258139859af16) for inspiration

**Comment by 10kumaranurag01** [comment]
@akshatshukla13 Make a new PR with changes suggested by @XronTrix10  and make a new PR.

**Comment by akshatshukla13** [comment]
Sure. Looking into it.
