### ISSUE TITLE
[FEATURE] Cookie based authentication with middleware

### ISSUE THREAD

**Issue by XronTrix10** [10kumaranurag01/todo-done#43]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently the frontend uses localStorage to store the JWT like standard react application which is not recommended and causes bugs and improper authentication management. 

### Proposed Solution

This project should take the advantage of Next.js server side features such as cookie based authentication and middleware to manage protected routes properly. It will help to redirect user from the server side itself without pushing from client side.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Using Next.js server side authentication

**Comment by 10kumaranurag01** [comment]
Ohk @XronTrix10 , saurabh is also working on authentication, work with him to complete this together.

**Comment by XronTrix10** [comment]
> Sure @10kumaranurag01, @XronTrix10 can we discuss tomorrow? Or u can ping me in discord sourabh782

Sure, we can talk. Discord - xrontrix

**Comment by XronTrix10** [comment]
@Sourabh782 I have changed the whole authentication system, now you can work on #8

**Comment by 10kumaranurag01** [comment]
@XronTrix10 Now as you have changed from jwt to cookie, the backend doesn't understand cookie now

**Comment by 10kumaranurag01** [comment]
@XronTrix10 Please fix the backend accordingly to support cookie authentication asap, the app is broken now!!!

**Comment by 10kumaranurag01** [comment]
Something is messed up, Dm me in twitter @XronTrix10

**Comment by Sourabh782** [comment]
hey @10kumaranurag01 @XronTrix10  is there any problem going?

**Comment by 10kumaranurag01** [comment]
@Sourabh782 Yes the auth system is broken right now.

**Comment by Sourabh782** [comment]
May ik what problem going on?

**Comment by 10kumaranurag01** [comment]
@Sourabh782 Dm me

**Comment by Sourabh782** [comment]
Any social handle? @10kumaranurag01
