### ISSUE TITLE
[FEATURE] Server Side Rendering

### ISSUE THREAD

**Issue by XronTrix10** [10kumaranurag01/todo-done#44]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

All the Pages are marked as "use client" directive which makes it a normal react application. Basically the browser downloads all the components, javascript bundle and renders the pages in the client side which significantly downgrades performance.

### Proposed Solution

SSR or Server side rendering should be used to the pages and non interactive components which will reduce client side rendering and improve performance 

### Do you want to work on this issue?

Yes

**Comment by 10kumaranurag01** [comment]
@XronTrix10 Go ahead, fork it, create a branch and make a PR.
