### ISSUE TITLE
Enhance readme.md

### ISSUE THREAD

**Issue by Aditijainnn** [10kumaranurag01/todo-done#5]
Readme.md looks ok but it will look great if it had dropdown features and some project pictures
Please assign this to me in Hacktoberfest

**Comment by 10kumaranurag01** [comment]
Fork the repo and add an new branch and make a PR. Thank you @Aditijainnn

**Comment by 10kumaranurag01** [comment]
@Aditijainnn Also add instructions to run the backend whose repository link is provided in the readme

**Comment by Aditijainnn** [comment]
Ok
