### ISSUE TITLE
Add Integration for Adding To-Dos to Google Calendar and Apple Calendar

### ISSUE THREAD

**Issue by vverma022** [10kumaranurag01/todo-done#52]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

This PR adds functionality to the to-do application allowing users to seamlessly add their tasks to both Google Calendar and Apple Calendar.

### Proposed Solution

To add integration for Google Calendar and Apple Calendar in the to-do app, the requirements include setting up a Google Cloud project with the Google Calendar API and implementing OAuth2 authentication to allow users to grant access to their calendars. Once authenticated, the app will use the calendar.events.insert API to create events for to-do tasks in Google Calendar. For Apple Calendar, the app will generate an .ics file (iCal format) containing the task details, which users can download and import into their Apple Calendar. The frontend will include buttons on the task page to “Add to Google Calendar” and “Add to Apple Calendar,” triggering the respective actions.

### Screenshots

![Untitled-2024-09-05-1600](https://github.com/user-attachments/assets/dd05e3f1-65d0-470c-9eb4-8e7b05a7da9d)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

1.	Google Calendar Integration:

- Users can now add tasks directly to their Google Calendar.

- Implemented OAuth2 authentication flow for user permissions.

- Created backend API to insert events into Google Calendar using calendar.events.insert.

- Google Calendar events are populated with the task title, description, and (optional) due date.

2.	Apple Calendar Integration (iCal):

- Added functionality to generate .ics files for Apple Calendar.

- Users can download the .ics file, which contains the details for the to-do

**Comment by 10kumaranurag01** [comment]
Go ahead @vverma022. Have fun contributing ☺️

**Comment by vverma022** [comment]
Has google OAuth been implemented ?

**Comment by 10kumaranurag01** [comment]
@vverma022 No, not yet
