### ISSUE TITLE
[BUG] Add Todo modal  

### ISSUE THREAD

**Issue by Bamof25th** [10kumaranurag01/todo-done#72]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

live website 

### Version of website/mobile (for example "v1.2.3")

latest one 

### Description

After creating a todo :  Form modal does not close or clear up the inputs .

> can make the form clear its input and modal to get closed after adding the todo 

### Steps to Reproduce

Goto /dashboard click on add todo button and try adding one todo

click on add button several times you will se it sends multiple requests .  

### Screenshots

![Screenshot 2024-10-17 160048](https://github.com/user-attachments/assets/c4ece690-8ed5-4ec5-9b9e-d3a4369b9682)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Will improve the use of hook to fix this bug by implementing required solution  .

**Comment by 10kumaranurag01** [comment]
@Bamof25th Go ahead

**Comment by Bamof25th** [comment]
I have done a PR kindly check
